server:
  port: 7011
  url: ${url.server}/login

spring:
  application:
    name: rekening-koran
  cloud:
    config:
      uri: ${url.cloud-config}
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    listener:
      simple:
        missing-queues-fatal: true
  messages:
    basename: messages/messages
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${url.eureka}/eureka/

# oauth
oauth2:
  tokenUrl: ${url.oauth-server}/login
  checkTokenUrl: ${url.oauth-server}/oauth/check_token
  client-id: fgc
  client-secret: secret
  client-scope: read,write
  client-password: password
  client-refresh-token: refresh_token

exclude:
  uris: /v2/api-docs,/ping,
  wildcards: swagger,favicon,login,menu,user,setting,lookup,profile,branch,member

swagger:
  url: ${url.swagger}

#logging:
#  config: config/logback-release.xml



---
spring:
  profiles: localhost
  datasource:
    url: jdbc:postgresql://34.101.176.117:5432/ocrdb
    driver-class-name: org.postgresql.Driver
    username: friscasagala9
    password: ocr123
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect

url:
  server: http://localhost:7011
  swagger: http://localhost:7011

---
#Database Postgres
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://34.101.176.117:5432/ocrdb
    driver-class-name: org.postgresql.Driver
    username: friscasagala9
    password: ocr123
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hikari:
        connectionTimeout: 120000
        idleTimeout: 120000
        maxLifetime: 240000
        maximumPoolSize: 20
        minimumIdle: 5

url:
#  server: http://danamon-ocr.co.id
  swagger: http://danamon-ocr.co.id

---
spring:
  profiles: staging
  datasource:
    url: jdbc:postgresql://34.101.176.117:5432/ocrdb
    driver-class-name: org.postgresql.Driver
    username: friscasagala9
    password: ocr123
    type: org.apache.tomcat.jdbc.pool.DataSource
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hikari:
        connectionTimeout: 120000
        idleTimeout: 120000
        maxLifetime: 240000
        maximumPoolSize: 20
        minimumIdle: 5

url:
#  server: http://danamon-ocr.co.id
  swagger: http://danamon-ocr.co.id

---

FileServiceImpl.java:47